client_id = '4fe38c597d7c41d2a418144a87d7d082'
client_secret = '7deaab2f08154a97905868d89919fc55'
redirect_uri = 'https://localhost:8888/callback/'

scope = "playlist-modify-private user-library-read playlist-read-private"
